# Generated by Django 5.0.4 on 2024-04-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_alter_coworking_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworking',
            name='description_is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coworking.category'),
        ),
    ]
